import type { Room } from '../types';

export const mockRooms: Room[] = [
  {
    accessible: true,
    amenities: ['Queen', 'Garden', 'Accessible'],
    bedType: 'Queen',
    capacity: '2 guests',
    connecting: false,
    floor: 'Ground Floor',
    guest: undefined,
    housekeeping: {
      assignedStaff: 'Pooja',
      estimatedFinish: 'Complete',
      inspection: 'Ready',
      started: '08:00',
      status: 'Ready',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '005',
    reservation: 'Available',
    roomType: 'Accessible Queen',
    stayDates: 'Available today',
    status: 'ready',
    timeline: [
      { time: '08:00', label: 'Cleaning Started' },
      { time: '08:35', label: 'Ready for Assignment' },
    ],
    view: 'Garden',
    vip: false,
  },
  {
    accessible: false,
    amenities: ['Queen', 'City', 'Connecting'],
    bedType: 'Queen',
    capacity: '2 guests',
    connecting: true,
    floor: 'First Floor',
    housekeeping: {
      assignedStaff: 'Nisha',
      estimatedFinish: 'Complete',
      inspection: 'Passed',
      started: '08:10',
      status: 'Ready',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '101',
    reservation: 'ST1871',
    roomType: 'Standard Queen',
    stayDates: 'Arrival 4:00 PM',
    status: 'ready',
    timeline: [
      { time: '08:10', label: 'Cleaning Started' },
      { time: '09:00', label: 'Ready for Assignment' },
    ],
    view: 'City',
    vip: false,
  },
  {
    accessible: false,
    amenities: ['Twin', 'Courtyard', 'Connecting'],
    bedType: 'Twin',
    bookingId: 'ST1856',
    capacity: '2 guests',
    connecting: true,
    floor: 'First Floor',
    guest: 'Rhea Malhotra',
    housekeeping: {
      assignedStaff: 'Kavita',
      estimatedFinish: '10:45',
      inspection: 'Pending',
      started: '10:14',
      status: 'Cleaning',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '102',
    reservation: 'ST1856',
    roomType: 'Deluxe Twin',
    stayDates: 'Guest waiting',
    status: 'cleaning',
    timeline: [
      { time: '10:05', label: 'Checkout Completed' },
      { time: '10:14', label: 'Cleaning Started' },
    ],
    view: 'Courtyard',
    vip: false,
  },
  {
    accessible: false,
    amenities: ['King', 'City', 'Desk'],
    bedType: 'King',
    bookingId: 'ST1838',
    capacity: '2 guests',
    connecting: false,
    floor: 'Second Floor',
    guest: 'Dev Sharma',
    housekeeping: {
      assignedStaff: 'Rekha',
      estimatedFinish: 'Complete',
      inspection: 'Occupied refresh complete',
      started: '07:10',
      status: 'Occupied',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '201',
    reservation: 'ST1838',
    roomType: 'Premium King',
    stayDates: 'Checkout tomorrow',
    status: 'occupied',
    stayHref: '/guest-stay/ST1842',
    timeline: [
      { time: '07:30', label: 'Room Refresh Completed' },
      { time: '10:12', label: 'Guest In House' },
    ],
    view: 'City',
    vip: false,
  },
  {
    accessible: false,
    amenities: ['King', 'City', 'Work Desk'],
    bedType: 'King',
    capacity: '2 guests',
    connecting: false,
    floor: 'Second Floor',
    housekeeping: {
      assignedStaff: 'Ravi',
      estimatedFinish: 'After engineering',
      inspection: 'Hold',
      started: '09:05',
      status: 'Hold',
    },
    maintenance: {
      engineer: 'Arjun',
      issue: 'AC not cooling',
      priority: 'High',
      status: 'In progress',
    },
    number: '202',
    reservation: 'Blocked',
    roomType: 'Premium King',
    stayDates: 'Unavailable',
    status: 'maintenance',
    timeline: [
      { time: '09:20', label: 'Maintenance Created' },
      { time: '09:30', label: 'Engineer Assigned' },
    ],
    view: 'City',
    vip: false,
  },
  {
    accessible: false,
    amenities: ['King', 'Courtyard', 'Desk'],
    bedType: 'King',
    bookingId: 'ST1849',
    capacity: '2 guests',
    connecting: false,
    floor: 'Third Floor',
    guest: 'Jaipur Textiles Group',
    housekeeping: {
      assignedStaff: 'Suman',
      estimatedFinish: '12:30',
      inspection: 'Pending',
      started: '11:05',
      status: 'Dirty',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '302',
    reservation: 'ST1849',
    roomType: 'Premium King',
    stayDates: 'Corporate arrival',
    status: 'dirty',
    timeline: [
      { time: '10:41', label: 'Guest Arrived Early' },
      { time: '11:05', label: 'Cleaning Started' },
    ],
    view: 'Courtyard',
    vip: false,
  },
  {
    accessible: false,
    amenities: ['King', 'Balcony', 'Garden'],
    bedType: 'King',
    bookingId: 'ST1842',
    capacity: '3 guests',
    connecting: false,
    floor: 'Fourth Floor',
    guest: 'Ananya Rao',
    housekeeping: {
      assignedStaff: 'Meena',
      estimatedFinish: 'Complete',
      inspection: 'Occupied refresh complete',
      started: '07:30',
      status: 'Occupied',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '402',
    reservation: 'ST1842',
    roomType: 'Premium Suite',
    stayDates: '28 Jun - 01 Jul',
    status: 'occupied',
    stayHref: '/guest-stay/ST1842',
    timeline: [
      { time: '09:42', label: 'Priority Cleaning Complete' },
      { time: '10:12', label: 'Guest Checked In' },
    ],
    view: 'Garden',
    vip: true,
  },
  {
    accessible: false,
    amenities: ['Suite', 'Balcony', 'City'],
    bedType: 'King',
    capacity: '3 guests',
    connecting: false,
    floor: 'Fourth Floor',
    housekeeping: {
      assignedStaff: 'Sana',
      estimatedFinish: 'Complete',
      inspection: 'Passed',
      started: '07:20',
      status: 'Ready',
    },
    maintenance: { engineer: 'None', issue: 'None', priority: 'None', status: 'Clear' },
    number: '501',
    reservation: 'ST1851',
    roomType: 'Signature Suite',
    stayDates: 'VIP arrival 11:30',
    status: 'reserved',
    timeline: [
      { time: '08:10', label: 'Cleaning Completed' },
      { time: '08:40', label: 'Held for VIP' },
    ],
    view: 'Garden and city',
    vip: true,
  },
  {
    accessible: false,
    amenities: ['Suite', 'City', 'Blocked'],
    bedType: 'King',
    capacity: '3 guests',
    connecting: false,
    floor: 'Fourth Floor',
    housekeeping: {
      assignedStaff: 'Sana',
      estimatedFinish: 'After repair',
      inspection: 'Blocked',
      started: 'Not started',
      status: 'Blocked',
    },
    maintenance: {
      engineer: 'Manoj',
      issue: 'Plumbing repair',
      priority: 'High',
      status: 'Open',
    },
    number: '506',
    reservation: 'Blocked',
    roomType: 'Signature Suite',
    stayDates: 'Unavailable',
    status: 'out-of-order',
    timeline: [
      { time: '07:55', label: 'Room Marked Out Of Order' },
      { time: '08:05', label: 'Maintenance Assigned' },
    ],
    view: 'City',
    vip: false,
  },
];
