export enum RoomOperationalStatus {
  READY = 'READY',
  OCCUPIED = 'OCCUPIED',
  NEEDS_CLEANING = 'NEEDS_CLEANING',
  INSPECTION = 'INSPECTION',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  MAINTENANCE = 'MAINTENANCE',
}
