import { UserRole } from './domain/user-role.enum';
import { allPermissions, Permission, Permissions } from './permissions';

export const rolePermissions: Record<UserRole, Permission[]> = {
  [UserRole.OWNER]: allPermissions,
  [UserRole.ADMIN]: allPermissions,
  [UserRole.MANAGER]: [
    Permissions.RoomsView,
    Permissions.RoomsManage,
    Permissions.GuestsView,
    Permissions.GuestsManage,
    Permissions.BookingsView,
    Permissions.BookingsManage,
    Permissions.ArrivalManage,
    Permissions.CheckinManage,
    Permissions.CheckoutManage,
    Permissions.StayView,
    Permissions.StayManage,
    Permissions.BillingView,
    Permissions.HousekeepingView,
    Permissions.HousekeepingManage,
    Permissions.EmployeesView,
    Permissions.EmployeesManage,
    Permissions.MaintenanceView,
    Permissions.OperationsView,
    Permissions.GuestRequestsView,
    Permissions.GuestRequestsManage,
    Permissions.ReportsView,
    Permissions.UsersView,
    Permissions.SessionsView,
  ],
  [UserRole.FRONT_DESK]: [
    Permissions.RoomsView,
    Permissions.RoomsManage,
    Permissions.GuestsView,
    Permissions.GuestsManage,
    Permissions.BookingsView,
    Permissions.BookingsManage,
    Permissions.ArrivalManage,
    Permissions.CheckinManage,
    Permissions.CheckoutManage,
    Permissions.StayView,
    Permissions.StayManage,
    Permissions.BillingView,
    Permissions.BillingManage,
    Permissions.HousekeepingView,
    Permissions.EmployeesView,
    Permissions.MaintenanceView,
    Permissions.OperationsView,
    Permissions.GuestRequestsView,
    Permissions.GuestRequestsManage,
  ],
  [UserRole.HOUSEKEEPING]: [
    Permissions.RoomsView,
    Permissions.RoomsStatusManage,
    Permissions.HousekeepingView,
    Permissions.HousekeepingManage,
    Permissions.EmployeesView,
    Permissions.OperationsView,
    Permissions.GuestRequestsView,
    Permissions.GuestRequestsManage,
  ],
  [UserRole.MAINTENANCE]: [
    Permissions.RoomsView,
    Permissions.RoomsStatusManage,
    Permissions.MaintenanceView,
    Permissions.MaintenanceManage,
    Permissions.OperationsView,
    Permissions.GuestRequestsView,
    Permissions.GuestRequestsManage,
  ],
  [UserRole.ACCOUNTS]: [
    Permissions.GuestsView,
    Permissions.BookingsView,
    Permissions.StayView,
    Permissions.BillingView,
    Permissions.BillingManage,
    Permissions.ReportsView,
  ],
  [UserRole.READ_ONLY]: [
    Permissions.RoomsView,
    Permissions.GuestsView,
    Permissions.BookingsView,
    Permissions.StayView,
    Permissions.BillingView,
    Permissions.HousekeepingView,
    Permissions.EmployeesView,
    Permissions.OperationsView,
    Permissions.GuestRequestsView,
  ],
};

export const getPermissionsForRole = (role: UserRole): Permission[] => rolePermissions[role] ?? [];
