export enum EmployeeDepartment {
  HOUSEKEEPING = 'HOUSEKEEPING',
  MAINTENANCE = 'MAINTENANCE',
  FRONT_DESK = 'FRONT_DESK',
  ACCOUNTS = 'ACCOUNTS',
  RESTAURANT = 'RESTAURANT',
  KITCHEN = 'KITCHEN',
  LAUNDRY = 'LAUNDRY',
  SECURITY = 'SECURITY',
  SPA = 'SPA',
  OTHER = 'OTHER',
}
