export enum AmenityCategory {
  CONNECTIVITY = 'CONNECTIVITY',
  COMFORT = 'COMFORT',
  ENTERTAINMENT = 'ENTERTAINMENT',
  SAFETY = 'SAFETY',
  SERVICE = 'SERVICE',
  ACCESSIBILITY = 'ACCESSIBILITY',
}
