// Common dropdown data for the Check-In and Guest forms.
// Kept intentionally short: the top-of-mind picks for an Indian hotel front desk.

export const COMMON_NATIONALITIES = [
  'INDIAN',
  'AMERICAN',
  'AUSTRALIAN',
  'BANGLADESHI',
  'BRITISH',
  'CANADIAN',
  'CHINESE',
  'FRENCH',
  'GERMAN',
  'ITALIAN',
  'JAPANESE',
  'NEPALI',
  'RUSSIAN',
  'SINGAPOREAN',
  'SRI LANKAN',
  'OTHER',
];

export const COMMON_COUNTRIES = [
  'India',
  'United States',
  'United Kingdom',
  'United Arab Emirates',
  'Singapore',
  'Australia',
  'Canada',
  'Germany',
  'France',
  'Japan',
  'Nepal',
  'Bangladesh',
  'Sri Lanka',
  'Other',
];

export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const PURPOSE_OF_VISIT = [
  'Leisure',
  'Business',
  'Family / Wedding',
  'Event / Conference',
  'Medical',
  'Educational',
  'Transit',
  'Other',
];
