export enum ReservationRateSnapshotTrigger {
  INITIAL = 'INITIAL',
  RATE_PLAN_CHANGE = 'RATE_PLAN_CHANGE',
  DATE_CHANGE = 'DATE_CHANGE',
  ROOM_TYPE_CHANGE = 'ROOM_TYPE_CHANGE',
  OCCUPANCY_CHANGE = 'OCCUPANCY_CHANGE',
  STAY_EXTENSION = 'STAY_EXTENSION',
  AMENDMENT = 'AMENDMENT',
}
